import { describe, it, expect } from 'vitest'
import { buildModel } from '../src/model.js'
import { emitDocs } from '../src/docs-emit.js'
import { adapters } from '../src/adapters/index.js'
import { claudeCode } from '../src/adapters/claude-code.js'
import type { HarnessAdapter } from '../src/adapters/types.js'

const model = buildModel('fixtures/kitchen-sink')

const fullSupport = {
  skills: 'full',
  commands: 'full',
  agents: 'full',
  hooks: 'full',
  mcp: 'full',
  bootstrap: 'full',
} as const

function adapterWithInstallDoc(name: string, body: string): HarnessAdapter {
  return {
    name,
    support: fullSupport,
    emit: () => ({ files: [], warnings: [] }),
    installDoc: () => body,
  }
}

function adapterWithoutInstallDoc(name: string): HarnessAdapter {
  return { name, support: fullSupport, emit: () => ({ files: [], warnings: [] }) }
}

describe('emitDocs install-doc files', () => {
  it('emits docs/install/<name>.md only for adapters implementing installDoc', () => {
    const withDoc = adapterWithInstallDoc('kimi', 'Body text for kimi.')
    const withoutDoc = adapterWithoutInstallDoc('codex')
    const files = emitDocs(model, [withDoc, withoutDoc])
    expect(files.some((f) => f.path === 'docs/install/kimi.md')).toBe(true)
    expect(files.some((f) => f.path === 'docs/install/codex.md')).toBe(false)
  })

  it('wraps the installDoc body with a generated marker and a heading naming the plugin and the mapped display name', () => {
    const withDoc = adapterWithInstallDoc('kimi', 'Body text for kimi.')
    const files = emitDocs(model, [withDoc])
    const file = files.find((f) => f.path === 'docs/install/kimi.md')!
    const lines = file.content.split('\n')
    expect(lines[0]).toBe('<!-- GENERATED by everyharness — edit everyharness.yaml instead -->')
    expect(lines[1]).toBe('')
    expect(lines[2]).toBe('# Installing kitchen-sink on Kimi Code')
    expect(lines[3]).toBe('')
    expect(file.content).toContain('Body text for kimi.')
    expect(file.content.endsWith('\n')).toBe(true)
  })

  it('falls back to the adapter name itself when it has no entry in the display-name map', () => {
    const withDoc = adapterWithInstallDoc('totally-unmapped-adapter', 'Body.')
    const files = emitDocs(model, [withDoc])
    const file = files.find((f) => f.path === 'docs/install/totally-unmapped-adapter.md')!
    expect(file.content).toContain('# Installing kitchen-sink on totally-unmapped-adapter')
  })

  it('emits no install-doc files at all when no active adapter implements installDoc', () => {
    const files = emitDocs(model, [adapterWithoutInstallDoc('codex'), adapterWithoutInstallDoc('devin')])
    expect(files.some((f) => f.path.startsWith('docs/install/'))).toBe(false)
  })
})

describe('emitDocs support-matrix.md', () => {
  it('is always emitted, independent of the active adapter list', () => {
    const files = emitDocs(model, [])
    const file = files.find((f) => f.path === 'docs/support-matrix.md')
    expect(file).toBeDefined()
  })

  it('starts with the generated marker and a heading naming the plugin', () => {
    const files = emitDocs(model, [])
    const content = files.find((f) => f.path === 'docs/support-matrix.md')!.content
    const lines = content.split('\n')
    expect(lines[0]).toBe('<!-- GENERATED by everyharness — edit everyharness.yaml instead -->')
    expect(lines[1]).toBe('')
    expect(lines[2]).toBe('# kitchen-sink harness support matrix')
  })

  it('has exact content for the full 11-adapter registry: all rows plus the Notes section', () => {
    const content = emitDocs(model, adapters).find((f) => f.path === 'docs/support-matrix.md')!.content
    expect(content).toBe(
      [
        '<!-- GENERATED by everyharness — edit everyharness.yaml instead -->',
        '',
        '# kitchen-sink harness support matrix',
        '',
        '| Harness | skills | commands | agents | hooks | mcp | bootstrap |',
        '|---|---|---|---|---|---|---|',
        '| claude-code | full | full | full | full | full | full |',
        '| cursor | full | none | none | partial | none | full |',
        '| codex | full | none | none | none | none | partial |',
        '| devin | full | none | none | none | none | none |',
        '| kimi | full | none | none | none | none | partial |',
        '| gemini | full | full | none | none | none | full |',
        '| opencode | full | full | partial | none | none | full |',
        '| pi | full | none | none | none | none | full |',
        '| hermes | full | none | none | none | none | full |',
        '| agent-plugins-1.0 | full | none | none | none | full | none |',
        '| agents-marketplace | none | none | none | none | none | none |',
        '',
        '## Notes',
        '',
        "- `agents-marketplace`'s row is all `none`: droid, grok, and copilot ride the claude-code layout via the marketplace descriptor it emits; the row reflects only agents-marketplace's own emission, not what those clients receive through that descriptor.",
        "- codex's `bootstrap: partial` means native skill discovery only, with no active injection hook; devin's `bootstrap: none` means no injection mechanism is documented at all.",
        '- Repos consuming shell-hook output should add `hooks/everyharness/* text eol=lf` to .gitattributes or accept drift warnings on autocrlf checkouts.',
        '',
      ].join('\n'),
    )
  })
})

describe('emitDocs with the real claude-code adapter (proves the pipe end to end)', () => {
  it('emits docs/install/claude-code.md with the marker, heading, and installDoc body', () => {
    const files = emitDocs(model, [claudeCode])
    const file = files.find((f) => f.path === 'docs/install/claude-code.md')!
    expect(file.content).toBe(
      [
        '<!-- GENERATED by everyharness — edit everyharness.yaml instead -->',
        '',
        '# Installing kitchen-sink on Claude Code',
        '',
        claudeCode.installDoc!(model),
        '',
      ].join('\n'),
    )
  })

  it('emits only docs/install/claude-code.md and docs/support-matrix.md for the real 11-adapter registry (no adapter but claude-code implements installDoc yet)', () => {
    const files = emitDocs(model, adapters)
    const installDocPaths = files.filter((f) => f.path.startsWith('docs/install/')).map((f) => f.path)
    expect(installDocPaths).toEqual(['docs/install/claude-code.md'])
  })
})
