import { describe, it, expect } from 'vitest'
import { buildModel } from '../src/model.js'
import { emitDocs } from '../src/docs-emit.js'
import type { HarnessAdapter } from '../src/adapters/types.js'

const model = buildModel('fixtures/kitchen-sink')

const fullSupport = {
  skills: 'full',
  commands: 'full',
  agents: 'full',
  hooks: 'full',
  mcp: 'full',
  bootstrap: 'full',
} as const

function adapterWithInstallDoc(name: string, body: string): HarnessAdapter {
  return {
    name,
    support: fullSupport,
    emit: () => ({ files: [], warnings: [] }),
    installDoc: () => body,
  }
}

function adapterWithoutInstallDoc(name: string): HarnessAdapter {
  return { name, support: fullSupport, emit: () => ({ files: [], warnings: [] }) }
}

describe('emitDocs install-doc files', () => {
  it('emits docs/install/<name>.md only for adapters implementing installDoc', () => {
    const withDoc = adapterWithInstallDoc('kimi', 'Body text for kimi.')
    const withoutDoc = adapterWithoutInstallDoc('codex')
    const files = emitDocs(model, [withDoc, withoutDoc])
    expect(files.some((f) => f.path === 'docs/install/kimi.md')).toBe(true)
    expect(files.some((f) => f.path === 'docs/install/codex.md')).toBe(false)
  })

  it('wraps the installDoc body with a generated marker and a heading naming the plugin and the mapped display name', () => {
    const withDoc = adapterWithInstallDoc('kimi', 'Body text for kimi.')
    const files = emitDocs(model, [withDoc])
    const file = files.find((f) => f.path === 'docs/install/kimi.md')!
    const lines = file.content.split('\n')
    expect(lines[0]).toBe('<!-- GENERATED by everyharness — edit everyharness.yaml instead -->')
    expect(lines[1]).toBe('')
    expect(lines[2]).toBe('# Installing kitchen-sink on Kimi Code')
    expect(lines[3]).toBe('')
    expect(file.content).toContain('Body text for kimi.')
    expect(file.content.endsWith('\n')).toBe(true)
  })

  it('falls back to the adapter name itself when it has no entry in the display-name map', () => {
    const withDoc = adapterWithInstallDoc('totally-unmapped-adapter', 'Body.')
    const files = emitDocs(model, [withDoc])
    const file = files.find((f) => f.path === 'docs/install/totally-unmapped-adapter.md')!
    expect(file.content).toContain('# Installing kitchen-sink on totally-unmapped-adapter')
  })

  it('emits no install-doc files at all when no active adapter implements installDoc', () => {
    const files = emitDocs(model, [adapterWithoutInstallDoc('codex'), adapterWithoutInstallDoc('devin')])
    expect(files.some((f) => f.path.startsWith('docs/install/'))).toBe(false)
  })
})

describe('emitDocs support-matrix.md', () => {
  it('is always emitted, independent of the active adapter list', () => {
    const files = emitDocs(model, [])
    const file = files.find((f) => f.path === 'docs/support-matrix.md')
    expect(file).toBeDefined()
  })

  it('starts with the generated marker and a heading naming the plugin', () => {
    const files = emitDocs(model, [])
    const content = files.find((f) => f.path === 'docs/support-matrix.md')!.content
    const lines = content.split('\n')
    expect(lines[0]).toBe('<!-- GENERATED by everyharness — edit everyharness.yaml instead -->')
    expect(lines[1]).toBe('')
    expect(lines[2]).toBe('# kitchen-sink harness support matrix')
  })
})
