import { deepMerge } from '../fileset.js'
import type { GeneratedFile } from '../fileset.js'
import type { PluginModel, CommandRef } from '../model.js'
import type { HarnessAdapter, EmitResult } from './types.js'
import { json } from './shared.js'
import { generatedBootstrap, GENERATED_BOOTSTRAP_PATH } from '../bootstrap/generated.js'

const GENERATED_MARKER = '<!-- GENERATED by everyharness — edit everyharness.yaml instead -->'
const GENERATED_MARKER_TOML = '# GENERATED by everyharness — edit everyharness.yaml instead'

function extensionManifest(model: PluginModel): Record<string, unknown> {
  const { config } = model
  const manifest: Record<string, unknown> = {
    name: config.name,
    description: config.description,
    version: config.version,
    contextFileName: 'GEMINI.md',
  }
  const override = config.harnesses.overrides.gemini
  return override ? (deepMerge(manifest, override) as Record<string, unknown>) : manifest
}

// TOML basic-string escaping: backslash first (so an escaped backslash isn't
// re-escaped by the quote pass), then double-quote.
function tomlEscape(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"')
}

// Gemini extension commands (commands/<name>.toml, extension root == plugin
// root) support only a single {{args}} placeholder, not Claude's positional
// $1/$2 syntax -- ground truth: gemini-cli docs/cli/custom-commands. $1-style
// syntax has no equivalent, so it is passed through verbatim with a warning
// rather than dropped or rejected.
function commandFile(cmd: CommandRef, warnings: string[]): GeneratedFile {
  if (/\$\d/.test(cmd.body)) {
    warnings.push(
      `command "${cmd.name}" uses positional arguments; Gemini supports only {{args}} — positional syntax passed through verbatim`,
    )
  }
  let body = cmd.body.replace(/\$ARGUMENTS(?!\w)/g, '{{args}}')
  // TOML basic multiline strings treat `\` as the start of an escape
  // sequence, so a literal backslash in the body (e.g. a regex or a Windows
  // path) must be doubled. This must run before the `"""` handling below --
  // otherwise the backslash that escaping introduces there would itself get
  // re-escaped.
  body = body.replace(/\\/g, '\\\\')
  // A literal `"""` in the body would prematurely close the TOML basic
  // multiline string. Escaping one of the three quotes (`""\"`) decodes back
  // to `"""` on parse, so the round-tripped prompt content is unchanged.
  if (body.includes('"""')) {
    body = body.replaceAll('"""', '""\\"')
    warnings.push(`command "${cmd.name}" body contains triple quotes; escaped for TOML`)
  }
  // Normalize the body's trailing newlines to exactly one before the closing
  // delimiter -- the source body already ends in `\n` (frontmatter parsing
  // leaves it), so appending a bare `\n"""` without trimming would leave a
  // blank line before the close.
  body = body.replace(/\n+$/, '')

  const lines = [GENERATED_MARKER_TOML]
  if (cmd.description) lines.push(`description = "${tomlEscape(cmd.description)}"`)
  lines.push('prompt = """')
  const content = `${lines.join('\n')}\n${body}\n"""\n`
  return { path: `commands/${cmd.name}.toml`, content }
}

function contextFile(model: PluginModel): string {
  const { config } = model
  if (config.bootstrap.kind === 'skill') {
    const skillName = config.bootstrap.skill
    const skill = model.skills.find((s) => s.name === skillName)
    if (!skill) {
      // buildModel validates the bootstrap skill exists before adapters run.
      throw new Error(`bootstrap skill "${skillName}" not found (buildModel should have validated this)`)
    }
    return `${GENERATED_MARKER}\n\n@./${skill.dir}/SKILL.md\n`
  }
  if (config.bootstrap.kind === 'generate') {
    return `${GENERATED_MARKER}\n\n@./${GENERATED_BOOTSTRAP_PATH}\n`
  }
  return `${GENERATED_MARKER}\n\nThis plugin provides skills in ${config.components.skills}/.\n`
}

export const gemini: HarnessAdapter = {
  name: 'gemini',
  support: {
    skills: 'full',
    commands: 'full',
    agents: 'none',
    hooks: 'none',
    mcp: 'none',
    bootstrap: 'full',
  },
  emit(model: PluginModel): EmitResult {
    const { config } = model
    const warnings: string[] = []
    const files: GeneratedFile[] = [
      { path: 'gemini-extension.json', content: json(extensionManifest(model)) },
      { path: 'GEMINI.md', content: contextFile(model) },
      ...model.commands.map((c) => commandFile(c, warnings)),
    ]
    if (config.bootstrap.kind === 'generate') {
      files.push({ path: GENERATED_BOOTSTRAP_PATH, content: generatedBootstrap(model) })
    }

    const contextFileNameOverride = config.harnesses.overrides.gemini?.contextFileName
    if (typeof contextFileNameOverride === 'string' && contextFileNameOverride !== 'GEMINI.md') {
      warnings.push(
        `contextFileName override "${contextFileNameOverride}" does not match the emitted GEMINI.md; the harness will look for a missing file`,
      )
    }

    if (model.hooks !== undefined) warnings.push('hooks are not emitted for gemini')
    if (model.agents.length) warnings.push('agents are not emitted for gemini')
    if (model.mcp !== undefined) warnings.push('mcp servers are not emitted for gemini in v1 (Plan 3)')

    return { files, warnings }
  },
}
