import { deepMerge } from '../fileset.js'
import type { GeneratedFile } from '../fileset.js'
import type { PluginModel } from '../model.js'
import type { HarnessAdapter, EmitResult } from './types.js'
import { json } from './shared.js'

const GENERATED_MARKER = '<!-- GENERATED by everyharness — edit everyharness.yaml instead -->'

function extensionManifest(model: PluginModel): Record<string, unknown> {
  const { config } = model
  const manifest: Record<string, unknown> = {
    name: config.name,
    description: config.description,
    version: config.version,
    contextFileName: 'GEMINI.md',
  }
  const override = config.harnesses.overrides.gemini
  return override ? (deepMerge(manifest, override) as Record<string, unknown>) : manifest
}

function contextFile(model: PluginModel): string {
  const { config } = model
  if (config.bootstrap.kind === 'skill') {
    const skillName = config.bootstrap.skill
    const skill = model.skills.find((s) => s.name === skillName)
    if (!skill) {
      // buildModel validates the bootstrap skill exists before adapters run.
      throw new Error(`bootstrap skill "${skillName}" not found (buildModel should have validated this)`)
    }
    return `${GENERATED_MARKER}\n\n@./${skill.dir}/SKILL.md\n`
  }
  return `${GENERATED_MARKER}\n\nThis plugin provides skills in ${config.components.skills}/.\n`
}

export const gemini: HarnessAdapter = {
  name: 'gemini',
  support: {
    skills: 'full',
    commands: 'none',
    agents: 'none',
    hooks: 'none',
    mcp: 'none',
    bootstrap: 'full',
  },
  emit(model: PluginModel): EmitResult {
    const { config } = model
    const warnings: string[] = []
    const files: GeneratedFile[] = [
      { path: 'gemini-extension.json', content: json(extensionManifest(model)) },
      { path: 'GEMINI.md', content: contextFile(model) },
    ]

    const contextFileNameOverride = config.harnesses.overrides.gemini?.contextFileName
    if (typeof contextFileNameOverride === 'string' && contextFileNameOverride !== 'GEMINI.md') {
      warnings.push(
        `contextFileName override "${contextFileNameOverride}" does not match the emitted GEMINI.md; the harness will look for a missing file`,
      )
    }

    if (config.bootstrap.kind === 'generate') {
      warnings.push('bootstrap.generate is not implemented until Plan 3; falling back to none')
    }

    if (model.hooks !== undefined) warnings.push('hooks are not emitted for gemini')
    if (model.commands.length) warnings.push('commands are not translated to Gemini TOML in v1 (Plan 3)')
    if (model.agents.length) warnings.push('agents are not emitted for gemini')
    if (model.mcp !== undefined) warnings.push('mcp servers are not emitted for gemini in v1 (Plan 3)')

    return { files, warnings }
  },
}
