import type { PluginModel } from './model.js'
import type { HarnessAdapter } from './adapters/types.js'
import type { FileSet, GeneratedFile } from './fileset.js'
import { renderMatrix } from './matrix.js'

const GENERATED_MARKER = '<!-- GENERATED by everyharness — edit everyharness.yaml instead -->'

// Display names for docs/install/<name>.md headings and support-matrix.md
// prose. Deliberately hardcoded here rather than an adapter field (keeps
// HarnessAdapter minimal) — one more entry per adapter is a small, static
// cost the docs stage alone pays.
const DISPLAY_NAMES: Record<string, string> = {
  'claude-code': 'Claude Code',
  cursor: 'Cursor',
  codex: 'Codex',
  devin: 'Devin CLI',
  kimi: 'Kimi Code',
  gemini: 'Gemini CLI',
  opencode: 'OpenCode',
  pi: 'Pi',
  hermes: 'Hermes Agent',
  'agent-plugins-1.0': 'Agent Plugins 1.0 clients',
  'agents-marketplace': 'Factory Droid / Grok / Copilot (marketplace descriptor)',
}

function displayName(adapterName: string): string {
  return DISPLAY_NAMES[adapterName] ?? adapterName
}

function installDocFile(model: PluginModel, adapter: HarnessAdapter): GeneratedFile | undefined {
  if (!adapter.installDoc) return undefined
  const body = adapter.installDoc(model)
  const content =
    [
      GENERATED_MARKER,
      '',
      `# Installing ${model.config.name} on ${displayName(adapter.name)}`,
      '',
      body,
    ].join('\n') + '\n'
  return { path: `docs/install/${adapter.name}.md`, content }
}

// support-matrix.md's Notes section calls out three things that a plain
// support-level table can't: the agents-marketplace row is honest but
// misleading on its own (Design decision 2), codex vs. devin both show a
// non-'full' bootstrap for different reasons, and the CRLF/.gitattributes
// caveat for anyone consuming the emitted shell hooks (Design decision 2).
const NOTES = [
  "- `agents-marketplace`'s row is all `none`: droid, grok, and copilot ride the claude-code layout via the marketplace descriptor it emits; the row reflects only agents-marketplace's own emission, not what those clients receive through that descriptor.",
  "- codex's `bootstrap: partial` means native skill discovery only, with no active injection hook; devin's `bootstrap: none` means no injection mechanism is documented at all.",
  '- Repos consuming shell-hook output should add `hooks/everyharness/* text eol=lf` to .gitattributes or accept drift warnings on autocrlf checkouts.',
]

function supportMatrixFile(model: PluginModel): GeneratedFile {
  const content =
    [
      GENERATED_MARKER,
      '',
      `# ${model.config.name} harness support matrix`,
      '',
      renderMatrix().trimEnd(),
      '',
      '## Notes',
      '',
      ...NOTES,
    ].join('\n') + '\n'
  return { path: 'docs/support-matrix.md', content }
}

// Generates docs/install/<adapter-name>.md for each active adapter that
// implements installDoc, plus docs/support-matrix.md (always, independent of
// which adapters are active — it documents the tool's full registry, same
// as `everyharness matrix`). Called by generate() after adapter emission;
// the returned files go through the same collision/manifest path as any
// adapter's output.
export function emitDocs(model: PluginModel, activeAdapters: HarnessAdapter[]): FileSet {
  const files: FileSet = []
  for (const adapter of activeAdapters) {
    const file = installDocFile(model, adapter)
    if (file) files.push(file)
  }
  files.push(supportMatrixFile(model))
  return files
}
