import { describe, it, expect } from 'vitest'
import { mkdtempSync, mkdirSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { buildModel } from '../../src/model.js'
import { gemini } from '../../src/adapters/gemini.js'
import { adapters, getAdapter } from '../../src/adapters/index.js'

const model = buildModel('fixtures/kitchen-sink')

describe('adapter registry', () => {
  it('registers gemini', () => {
    expect(adapters.map((a) => a.name)).toContain('gemini')
    expect(getAdapter('gemini')).toBe(gemini)
  })
})

describe('gemini adapter', () => {
  const result = gemini.emit(model)
  const byPath = Object.fromEntries(result.files.map((f) => [f.path, f.content]))

  it('emits gemini-extension.json with the exact ground-truth shape', () => {
    const manifest = JSON.parse(byPath['gemini-extension.json'])
    expect(manifest).toEqual({
      name: 'kitchen-sink',
      description: 'Fixture plugin exercising every component type',
      version: '0.1.0',
      contextFileName: 'GEMINI.md',
    })
  })

  it('emits GEMINI.md with the marker and the bootstrap skill @-include', () => {
    expect(byPath['GEMINI.md']).toBe(
      '<!-- GENERATED by everyharness — edit everyharness.yaml instead -->\n\n@./skills/using-kitchen-sink/SKILL.md\n',
    )
  })

  it('warns about hooks, commands, agents, and mcp not being emitted for gemini', () => {
    expect(result.warnings).toEqual([
      'hooks are not emitted for gemini',
      'commands are not translated to Gemini TOML in v1 (Plan 3)',
      'agents are not emitted for gemini',
      'mcp servers are not emitted for gemini in v1 (Plan 3)',
    ])
  })

  it('declares expected support levels', () => {
    expect(gemini.support).toEqual({
      skills: 'full',
      commands: 'none',
      agents: 'none',
      hooks: 'none',
      mcp: 'none',
      bootstrap: 'full',
    })
  })
})

describe('gemini adapter with harnesses.overrides.gemini', () => {
  it('deep-merges override fields into gemini-extension.json', () => {
    const dir = mkdtempSync(join(tmpdir(), 'eh-gemini-override-'))
    writeFileSync(
      join(dir, 'everyharness.yaml'),
      [
        'name: override-demo',
        'version: 1.0.0',
        'description: override fixture for gemini extension metadata',
        'harnesses:',
        '  overrides:',
        '    gemini:',
        '      contextFileName: CUSTOM.md',
      ].join('\n'),
    )
    const overrideModel = buildModel(dir)
    const result = gemini.emit(overrideModel)
    const manifest = JSON.parse(result.files.find((f) => f.path === 'gemini-extension.json')!.content)
    expect(manifest.contextFileName).toBe('CUSTOM.md')
  })

  it('warns that a contextFileName override does not match the emitted GEMINI.md', () => {
    const dir = mkdtempSync(join(tmpdir(), 'eh-gemini-override-'))
    writeFileSync(
      join(dir, 'everyharness.yaml'),
      [
        'name: override-demo',
        'version: 1.0.0',
        'description: override fixture for gemini extension metadata',
        'harnesses:',
        '  overrides:',
        '    gemini:',
        '      contextFileName: CUSTOM.md',
      ].join('\n'),
    )
    const overrideModel = buildModel(dir)
    const result = gemini.emit(overrideModel)
    expect(result.warnings).toContain(
      'contextFileName override "CUSTOM.md" does not match the emitted GEMINI.md; the harness will look for a missing file',
    )
  })
})

describe('gemini adapter without a bootstrap skill', () => {
  it('emits GEMINI.md with a skills-location note and no @-include', () => {
    const dir = mkdtempSync(join(tmpdir(), 'eh-gemini-none-'))
    writeFileSync(
      join(dir, 'everyharness.yaml'),
      'name: no-bootstrap\nversion: 1.0.0\ndescription: no bootstrap fixture\nbootstrap:\n  none: true\n',
    )
    mkdirSync(join(dir, 'skills', 'demo'), { recursive: true })
    writeFileSync(
      join(dir, 'skills', 'demo', 'SKILL.md'),
      '---\nname: demo\ndescription: demo skill for gemini none-mode test\n---\n\nBody.\n',
    )
    const noneModel = buildModel(dir)
    const result = gemini.emit(noneModel)
    const geminiMd = result.files.find((f) => f.path === 'GEMINI.md')!.content
    expect(geminiMd).toContain('This plugin provides skills in skills/.')
    expect(geminiMd).not.toContain('@./')
  })
})

describe('gemini adapter with bootstrap.generate', () => {
  it('emits GEMINI.md @-including the generated bootstrap.md, and the file itself', () => {
    const dir = mkdtempSync(join(tmpdir(), 'eh-gemini-generate-'))
    writeFileSync(
      join(dir, 'everyharness.yaml'),
      'name: generate-bootstrap\nversion: 1.0.0\ndescription: bootstrap.generate fixture\nbootstrap:\n  generate: true\n',
    )
    const generateModel = buildModel(dir)
    const result = gemini.emit(generateModel)
    const geminiMd = result.files.find((f) => f.path === 'GEMINI.md')!.content
    expect(geminiMd).toBe(
      '<!-- GENERATED by everyharness — edit everyharness.yaml instead -->\n\n@./hooks/everyharness/bootstrap.md\n',
    )
    const bootstrapMd = result.files.find((f) => f.path === 'hooks/everyharness/bootstrap.md')
    expect(bootstrapMd?.content).toContain('# generate-bootstrap plugin')
  })
})
